### ISSUE TITLE
Support for backends?

### ISSUE THREAD

**Issue by devinus** [play-co/hermes#23]
Are there any plans to support e.g. the Cassandra backend?

**Comment by ZackGC** [comment]
All of the backends supported by Titan are supported by Hermes. In particular, our company and at least one other company has used Hermes successfully with Cassandra. 

Checkout out the [Opening Graphs](https://github.com/gameclosure/hermes/wiki/Opening-graphs) portion of the wiki.

**Comment by devinus** [comment]
@ZackGC You're right, I'm sorry I didn't catch that before I opened the issue. The readme confused me when it specified "embedded Titan graphs."

**Comment by devinus** [comment]
I've been intending to write this library for some time, and glad that this looks so nice already!

**Comment by ZackGC** [comment]
No worries! The documentation for the project is still being written all the time and there are definitely aspects of the library that aren't as well documented as they should be by now. 

Would the phrasing "embedded Titan instances" be better? We know what we are doing with Hermes but we are still finding the words that best explain it to other people. 

If you have any questions about or ideas for this project shoot me an email (zack@gameclosure.com).

**Comment by devinus** [comment]
@ZackGC I think "embedded" was the confusing part. Perhaps "Titan graphs" or even just "Titan" would be enough.

**Comment by zmaril** [comment]
Switched to just "Titan" on the readme. It reads much better now. Thanks!
