### ISSUE TITLE
edges/edges-between returns null, also throws IllegalStateException in REPL

### ISSUE THREAD

**Issue by shirlenator** [play-co/hermes#32]
edges-between returns nil, even though using gremlin/query returns the edge. 

Separate, but probably related issue: I tried this in the REPL and got the following exception. 

``` clojure
user=> (def shilei (g/transact! (v/create! {:name "shilei"})))
#'user/shilei
user=> (def friend (g/transact! (v/create! {:name "friend"})))
#'user/friend
user=> (g/transact! (e/upconnect! (v/refresh shilei) (v/refresh friend) "has-phone"))
#{#<PersistLabeledTitanEdge e[800017:40004:36028797018964038][40004-has-phone->40008]>}
user=> (g/transact! (e/edges-between (v/refresh shilei) (v/refresh friend)))
IllegalStateException Operation cannot be executed because the enclosing transaction is closed  com.thinkaurelius.titan.core.TitanException.transactionNotOpenException   (TitanException.java:53)
```

**Comment by zmaril** [comment]
Please split this up into two issues next time, having them reference each other (just in case). 

"edges-between returns nil, even though using gremlin/query returns the edge."
1. Can you provide a test situation? 

"Separate, but probably related issue"
2. I can reproduce this. Looks like it is a problem within `edge.clj`.

**Comment by zmaril** [comment]
2 . Added in [a test](https://github.com/gameclosure/hermes/blob/728e680a74e85c96201982272bc66f405aeacbd0/test/hermes/persistent/edge_test.clj#L19) for this problem. It passes but I can still get the REPL to barf like you describe. It might have something to do with lazy evaluation on the REPL.

**Comment by zmaril** [comment]
2 . Not the REPL. I can reproduce this within example.clj. Unsure of what's going on.

**Comment by zmaril** [comment]
2 . Figured it out. It's the difference between

``` clojure
(def shilei (g/transact! (v/create! {:name "shilei"})))
(def friend (g/transact! (v/create! {:name "friend"})))
(g/transact! (println (e/upconnect! (v/refresh shilei) (v/refresh friend) "has-phone")))
(g/transact! (println (e/edges-between (v/refresh shilei) (v/refresh friend))))
```

And this: 

``` clojure
(def shilei (g/transact! (v/create! {:name "shilei"})))
(def friend (g/transact! (v/create! {:name "friend"})))
(println (g/transact!  (e/upconnect! (v/refresh shilei) (v/refresh friend) "has-phone")))
(println (g/transact! (e/edges-between (v/refresh shilei) (v/refresh friend))))
```

If you print out the edge during the transaction, everything is fine. This is a Titan issue; it looks like edges are holding on to stale references to their end nodes.

**Comment by zmaril** [comment]
See [https://github.com/thinkaurelius/titan/issues/148](for Titan issue).
