### ISSUE TITLE
Clear database before testing

### ISSUE THREAD

**Issue by zmaril** [play-co/hermes#33]
How can we clear out the database before we run the test suite?

**Comment by ghost** [comment]
if you use berkeleydb ie. (g/open path-here)
then maybe either (1) always use the same path (same subdir in the tmp dir) and delete the folder (at the beginning of) on :every test(or :once when the tests are about to run) by using fixtures, or (2) always create a subdir in the tmp dir and using fixtures can clear it out (at the end) when all (:once) or each (:every) of the tests is done.

I'm currently trying to do that part (2) in my context.

**Comment by zmaril** [comment]
That is the current plan actually. It shouldn't take more than five minutes to make the switch and make sure it still works. I do worry about there being differences in regard to concurrency and the various back ends. I've seen some code, pmap in particular, that works fine with cassandra but has trouble with berkelydb (and vice versa even). It's something that I'd like to test further but haven't taken the time to sort out.

**Comment by ghost** [comment]
it's taking me hours 'cause I'm a noob (not just clojure-wise) :) , just saying.
 but I did enjoy making the unique subdir thingy it's kinda fun

just to see the noobness: :))
https://github.com/DeMLinkS/demlinks/blob/01ff55fda872a087bb3ae52aa79a95bac03ee724/src/runtime/q.clj#L991

**Comment by ghost** [comment]
looks like there needs to be a way to tell titan to close the storage? or is this just by closing some transaction?
I mean, just doing a simple `(g/open "path")` alone requires something to be done to close this, if I want to be able to delete the now-in-use-by-bdbje "path". Any ideas? thanks you.

**Comment by ghost** [comment]
oh it's `(.shutdown ^com.thinkaurelius.titan.graphdb.database.StandardTitanGraph (g/open "path" ))`
EDIT: or one that works for both: `(.shutdown ^com.tinkerpop.blueprints.Graph gr)` where `gr` is either of: `(def gr (g/open "path"))` [bdbje graph] and `(def gr (g/open))` [in memory graph] or even cassandra-backed graph (my guess)

**Comment by zmaril** [comment]
This has been fixed in 0.2.7 in my repo. All further development of this project will be happening there. 
https://github.com/zmaril/hermes
